apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: tb3kco3v8-nodejs-gitops
  description: This is GitOps manifest for tb3kco3v8-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: tb3kco3v8-nodejs
    janus-idp.io/tekton: tb3kco3v8-nodejs 
    backstage.io/kubernetes-id: tb3kco3v8-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:tb3kco3v8-nodejs
